version: '3.9'

networks:
  net:
    driver: bridge
  # traefik:
  #   external: true

services:
  server:
    # image: server
    image: ${REGISTRY_NAME}/${IMAGE_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8324 --log-config log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER}
      - CHROMA_SERVER_AUTH_CREDENTIALS_FILE=${CHROMA_SERVER_AUTH_CREDENTIALS_FILE}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS}
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=${CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER}
    ports:
      - "8324:8324"
    networks:
      - net
      - traefik
    expose:
      - 8324
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.chroma.rule=Host(`chroma.local`)"
    #   - "traefik.http.routers.chroma.entrypoints=chroma"
    #   - "traefik.http.services.chroma.loadbalancer.server.port=8324"

volumes:
  index_data:
    driver: local
  backups:
    driver: local
